import fs from 'node:fs';
import path from 'node:path';
import ignore from 'ignore';

const DEFAULT_PATTERNS = [
  'node_modules',
  'vendor',
  'dist',
  'build',
  '.next',
  '.nuxt',
  'coverage',
  '__pycache__',
  '*.pyc',
  '.venv',
  'venv',
  '_graph',
  '_graph/llm-cache',
  '_wiki',
  '.git',
  '.husky',
  '.idea',
  '.DS_Store',
  '.env',
  '.env.*',
  '*.min.js',
  '*.bundle.js',
  '*.lock',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'composer.lock',
  'Gemfile.lock',
  'poetry.lock',
];

// Directories/files that, if present in the repo root, indicate they should be ignored
const AUTO_DETECT = [
  { path: 'node_modules', pattern: 'node_modules' },
  { path: '.next', pattern: '.next' },
  { path: '.nuxt', pattern: '.nuxt' },
  { path: '__pycache__', pattern: '__pycache__' },
  { path: '.turbo', pattern: '.turbo' },
  { path: '.cache', pattern: '.cache' },
  { path: 'dist', pattern: 'dist' },
  { path: 'build', pattern: 'build' },
  { path: '.pytest_cache', pattern: '.pytest_cache' },
  { path: '.mypy_cache', pattern: '.mypy_cache' },
  { path: '.tox', pattern: '.tox' },
  { path: '.eggs', pattern: '.eggs' },
  { path: '*.egg-info', pattern: '*.egg-info' },
  { path: 'htmlcov', pattern: 'htmlcov' },
  { path: '.coverage', pattern: '.coverage' },
  { path: 'vendor', pattern: 'vendor/bundler' },
  { path: 'venv', pattern: 'venv' },
  { path: '.venv', pattern: '.venv' },
  { path: '.serverless', pattern: '.serverless' },
  { path: '.terraform', pattern: '.terraform' },
  { path: 'cdk.out', pattern: 'cdk.out' },
  { path: '.parcel-cache', pattern: '.parcel-cache' },
  { path: '.rollup.cache', pattern: '.rollup.cache' },
];

export function loadLoomIgnore(repoRoot) {
  const ig = ignore().add(DEFAULT_PATTERNS);
  const file = path.join(repoRoot, '.loomignore');
  if (fs.existsSync(file)) {
    const content = fs.readFileSync(file, 'utf8');
    ig.add(content);
  }
  return ig;
}

export function filterPaths(repoRoot, absPaths) {
  const ig = loadLoomIgnore(repoRoot);
  return absPaths.filter((p) => {
    const rel = path.relative(repoRoot, p);
    if (!rel || rel.startsWith('..')) return false;
    return !ig.ignores(rel);
  });
}

/**
 * Auto-generate a .loomignore file if one does not exist.
 * Scans the repo root for common build/cache directories that should be
 * excluded from analysis. Only creates the file if patterns are found.
 * Returns 'created', 'exists', or 'not-needed'.
 */
export function ensureIgnoreFile(repoRoot) {
  const ignorePath = path.join(repoRoot, '.loomignore');
  if (fs.existsSync(ignorePath)) return 'exists';

  const foundPatterns = [];
  for (const item of AUTO_DETECT) {
    const target = path.join(repoRoot, item.path);
    try {
      if (fs.existsSync(target)) {
        foundPatterns.push(item.pattern);
      }
    } catch {
      // skip
    }
  }

  if (foundPatterns.length === 0) return 'not-needed';

  const content = [
    '# .loomignore -- auto-generated by loom-memory',
    '# These directories/files were detected in your repo and excluded from analysis.',
    '# Edit freely: add or remove patterns as needed (gitignore syntax).',
    '',
    ...foundPatterns,
    '',
  ].join('\n');

  fs.writeFileSync(ignorePath, content, 'utf8');
  return 'created';
}
